config/routes.rb
Esiga::Application.routes.draw do

  devise_for :users, skip: :registrations, controllers: {
    sessions:  'authentication/sessions',
    passwords: 'authentication/passwords'
  }

  root to: 'home#index'

  resources :categories, only: [ :index, :show ]

  namespace :admin do
    root to: 'dashboard#index'
    resources :categories, except: :show
    resources :products,   except: :show
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products

  attr_accessible :name

  validates :name, presence: true, uniqueness: true

  before_destroy :clear_product_relations

  def self.for_select
    all.map { |category| [ category.name, category.id ] }
  end

  private

  def clear_product_relations
    Product.where(category_id: id).update_all(category_id: nil)
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::AdminController

  before_filter :new_category,  only: [ :new, :create ]
  before_filter :load_category, only: [ :edit, :update, :destroy ]

  def index
    @categories = Category.all
  end

  def new; end

  def create
    if @category.save
      redirect_to admin_categories_path
    else
      render action: :new
    end
  end

  def edit; end

  def update
    if @category.update_attributes(params[:category])
      redirect_to admin_categories_path
    else
      render action: :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to admin_categories_path
    end
  end

  private

  def new_category
    @category = Category.new(params[:category])
  end

  def load_category
    @category = Category.find(params[:id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :load_categories, only: [ :index, :show ]

  def index; end

  def show
    @category = Category.find(params[:id])
  end

  private

  def load_categories
    @categories = Category.all
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def categories_nav
    content_tag :ul, class: 'nav nav-tabs nav-stacked' do
      safe_join \
        @categories.map{ |category| category_tab(category) }
    end
  end

  private

  def category_tab(category)
    icon_class = 'chevron-right pull-right'

    content = safe_join([
      glyph(icon_class), category.name
    ])

    content_tag :li, current_tab(category) do
      link_to content, category_path(category)
    end
  end

  def current_tab(category)
    if category == @category
      return { class: 'active' }
    end
  end

end

app/views/admin/categories/_form.html.erb
<%= f.fields_container :name do %>
  <%= f.required_label :name, t('admin.categories.base.name') %>
  <%= f.text_field :name %>
<% end %>

<%= form_actions(admin_categories_path) %>

app/views/admin/categories/_items.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= t('admin.categories.base.name') %></th>
      <th><%= t('admin.base.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td class='actions'>
          <%= edit_button(edit_admin_category_path(category)) %>
          <%= delete_button(admin_category_path(category)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/categories/edit.html.erb
<div class='row'>
  <div class='span12'>
    <%= page_header %>

    <%= horizontal_form_for @category, url: admin_category_path(@category) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<div class='row'>
  <div class='span12'>
    <%= page_header(new_admin_category_path) %>
    <%= items_list(@categories) %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<div class='row'>
  <div class='span12'>
    <%= page_header %>

    <%= horizontal_form_for @category, url: admin_categories_path do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>