config/routes.rb
Esiga::Application.routes.draw do

  devise_for :users, skip: :registrations, controllers: {
    sessions:  'authentication/sessions',
    passwords: 'authentication/passwords'
  }

  root to: 'home#index'

  resources :categories, only: [ :index, :show ]

  namespace :admin do
    root to: 'dashboard#index'
    resources :categories, except: :show
    resources :products,   except: :show
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  belongs_to :category

  attr_accessible :name, :price, :category_id

  validates :name, presence: true, uniqueness: true

  validates_numericality_of :price,
    allow_nil: true, only_integer: true, greater_than_or_equal_to: 0

  def category_name
    category.try(:name)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController

  before_filter :new_product,  only: [ :new, :create ]
  before_filter :load_product, only: [ :edit, :update, :destroy ]

  def index
    @products = Product.all
  end

  def new; end

  def create
    if @product.save
      redirect_to admin_products_path
    else
      render action: :new
    end
  end

  def edit; end

  def update
    if @product.update_attributes(params[:product])
      redirect_to admin_products_path
    else
      render action: :edit
    end
  end

  def destroy
    if @product.destroy
      redirect_to admin_products_path
    end
  end

  private

  def new_product
    @product = Product.new(params[:product])
  end

  def load_product
    @product = Product.find(params[:id])
  end

end

app/views/admin/products/_form.html.erb
<% scope = [ :admin, :products, :base ] %>

<%= f.fields_container :name do %>
  <%= f.required_label :name, t(:name, scope: scope) %>
  <%= f.text_field :name %>
<% end %>

<%= f.fields_container :category_id do %>
  <%= f.label :category, t(:category, scope: scope) %>
  <%= f.select :category_id, Category.for_select, include_blank: t('.select_category') %>
<% end if category_exists? %>

<%= f.fields_container :price do %>
  <%= f.label :price, t(:price, scope: scope) %>
  <%= f.number_field :price, min: 0 %>
<% end %>

<%= form_actions(admin_products_path) %>

app/views/admin/products/_items.html.erb
<% scope = [ :admin, :products, :base ] %>

<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= t(:name, scope: scope) %></th>
      <th><%= t(:price, scope: scope) %></th>
      <th><%= t(:category, scope: scope) %></th>
      <th class='actions'>
        <%= t('admin.base.actions') %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= currency_price(product.price) %></td>
        <td><%= product.category_name %></td>
        <td class='actions'>
          <%= edit_button(edit_admin_product_path(product)) %>
          <%= delete_button(admin_product_path(product)) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/products/edit.html.erb
<div class='row'>
  <div class='span12'>
    <%= page_header %>

    <%= horizontal_form_for @product, url: admin_product_path(@product) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class='row'>
  <div class='span12'>
    <%= page_header(new_admin_product_path) %>
    <%= items_list(@products) %>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class='row'>
  <div class='span12'>
    <%= page_header %>

    <%= horizontal_form_for @product, url: admin_products_path do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>